### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rikvdkleij** [haskell-tools/haskell-tools#258]
To improve Intellij-Haskell plugin I need more information about (local) bindings. Some simple API to access your simplified AST tree.

So for example, GHC gives warning that identifier is not used. Currently I can only remove the identifier itself and not it's definition because I do not know where it ends. Especially not for local bindings.

I can also not recognize type signatures in where expressions and locate it's definition. Also adding type signatures to local bindings can not be supported because the location range of the binding is not known.

Can you help me in some way?

**Comment by nboldi** [comment]
If you want to generate our representation of the source, I would suggest using the `parseTyped` function from `Language.Haskell.Tools.Refactor.Prepare`. This returns a typed representation of the AST. Of course you should set up your GHC session before using it. (setting targets, dynflags, etc.). You can see this in action in the `Daemon`, `CLI` and `Session` modules. For a simpler example, you can check out the tests of the haskell-tools-refactor package.

> So for example, GHC gives warning that identifier is not used. Currently I can only remove the identifier itself and not it's definition because I do not know where it ends. Especially not for local bindings.

You can define a refactoring in the Haskell Tools framework that does it. Consult our [tutorials](https://github.com/haskell-tools/haskell-tools/wiki/Tutorials:-replace-data-with-newtype), and the predefined refactorings (`Language.Haskell.Tools.Refactor.Predefined.*` modules).

> I can also not recognize type signatures in where expressions and locate it's definition. Also adding type signatures to local bindings can not be supported because the location range of the binding is not known.

Please clarify your intentions here. Would you like to use Haskell Tools Refactor to generate type signatures for local bindings? Because this is already supported.

**Comment by rikvdkleij** [comment]
@nboldi Thanks for your reply.

I will have to use your tool as external tool, so by using it's CLI.

> If you want to generate our representation of the source, I would suggest using the parseTyped function from Language.Haskell.Tools.Refactor.Prepare. This returns a typed representation of the AST. Of course you should set up your GHC session before using it. (setting targets, dynflags, etc.). You can see this in action in the Daemon, CLI and Session modules. For a simpler example, you can check out the tests of the haskell-tools-refactor package.

So to get your representation of source I will have to add this to your tool and make it accessible by CLI?

> You can define a refactoring in the Haskell Tools framework that does it. Consult our tutorials, and the predefined refactorings (Language.Haskell.Tools.Refactor.Predefined.* modules).

This also has to be added to your tool, create it a new type of refactoring and make it accessible by CLI? 

> Please clarify your intentions here. Would you like to use Haskell Tools Refactor to generate type signatures for local bindings? Because this is already supported.

Yes, for adding type signatures to (local) bindings I can already use your tool.

**Comment by zjhmale** [comment]
@nboldi generate type signatures to local bindings can easily be done with your tool, but it seems no ways to check whether a local binding is already bound with a type signature or not so that we can show a warning for users to trigger quick fix to generate the missing type signature.

**Comment by nboldi** [comment]
@zjhmale It is one of my plans to be able to offer quick fixes for the selected source code. As a quick-and-dirty solution you could write a "refactoring" that does not change the code, but prints the source ranges of bindings without signature.

@rikvdkleij You can add a new refactoring to the CLI by modifying the `Language.Haskell.Tools.Refactor.Perform` module, where the predefined refactorings are registered. If you create a general refactoring, I can merge the changes into the haskell-tools repo, or if you just crate something that is needed for your IDE, than you can maintain a fork of the main repo.
