### ISSUE TITLE
examples for cli refactor

### ISSUE THREAD

**Issue by nrolland** [haskell-tools/haskell-tools#381]
it would be nice to have examples for the cli refactor 

There are many tests  here
https://github.com/haskell-tools/haskell-tools/tree/master/src/cli/examples/Project

But how to launch a proper CLI session on them is unclear.

What is a "package-roots" mentioned in the [documentation](https://github.com/haskell-tools/haskell-tools/blob/master/documentation/ht-refact.md) ?

**Comment by nboldi** [comment]
Packages roots are the directories where the `.cabal` file is located (in case of a cabal package) or the root directory of your modules otherwise.

For example to use one of the CLI examples (as it is done by the CLI test suite) you can run the following command from the root directory of the repository (on Windows):

```
stack exec ht-refact -- src\cli\examples\Project\has-cabal
```

As the result, the module `A` will be loaded and after selecting it, you can perform refactorings on it.

**Comment by nrolland** [comment]
Works fine, thank you ! 
I would definitely put a few full command line in the docs if it's not already there.
I can imagine that this tool is useful in very different contexts with different crowds, so targeted doc, like you did, is very useful to narrow the gap and integrate.
